scoring_engine/web/views/about.py
from flask import Blueprint, render_template
from scoring_engine.version import version
from scoring_engine.models.setting import Setting

mod = Blueprint('about', __name__)


@mod.route('/about')
def about():
    about_content = Setting.get_setting('about_page_content').value
    return render_template('about.html', version=version, about_content=about_content)

scoring_engine/web/views/auth.py
import uuid
from flask import flash, redirect, request, url_for, g, Blueprint, render_template
from flask_login import current_user, login_user, logout_user, LoginManager, login_required
from flask_wtf import FlaskForm

from wtforms import PasswordField, StringField
from wtforms.validators import InputRequired

from sqlalchemy.orm.exc import NoResultFound

from scoring_engine.db import session
from scoring_engine.models.user import User

mod = Blueprint("auth", __name__)
mod.secret_key = str(uuid.uuid4())


# Create the login_manager object here, but don't call init_app yet
# The init_app() call will be done inside create_app() in the main app setup
login_manager = LoginManager()


# You don't need to call init_app here, it's done in create_app()
# You can still define the user_loader function here, as it's needed for Flask-Login
@login_manager.user_loader
def load_user(id):
    return session.query(User).get(int(id))


# Define the before_request function
@mod.before_app_request
def get_current_user():
    g.user = current_user


@mod.before_request
def get_current_user():
    g.user = current_user


# Creating our login form
class LoginForm(FlaskForm):
    username = StringField(
        "inputUsername",
        [InputRequired()],
        render_kw={"class": "form-control", "placeholder": "Username", "required": "true", "autofocus": "true"},
    )
    password = PasswordField(
        "inputUsername",
        [InputRequired()],
        render_kw={"class": "form-control", "placeholder": "Password", "required": "true"},
    )


@mod.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        flash("You are already logged in.", "info")
        return redirect(url_for("welcome.home"))

    form = LoginForm()

    if form.errors:
        flash(form.errors, "danger")
        return render_template("login.html", form=form)

    if form.validate_on_submit():
        username = request.form.get("username")
        password = request.form.get("password")

        try:
            user = session.query(User).filter(User.username == username).one()
        except NoResultFound:
            flash("Invalid username or password. Please try again.", "danger")
            return render_template("login.html", form=form)

        if User.generate_hash(password, user.password) == user.password:
            user.authenticated = True
            session.add(user)
            session.commit()
            login_user(user, remember=True)

            if user.is_white_team:
                return redirect(request.values.get("next") or url_for("admin.status"))
            elif user.is_blue_team:
                return redirect(request.values.get("next") or url_for("services.home"))
            else:
                return redirect(request.values.get("next") or url_for("overview.home"))
        else:
            flash("Invalid username or password. Please try again.", "danger")
            return render_template("login.html", form=form)

    return render_template("login.html", form=form)


@mod.route("/unauthorized")
def unauthorized():
    return render_template("unauthorized.html")


@mod.route("/logout")
@login_required
def logout():
    user = current_user
    user.authenticated = False
    session.add(user)
    session.commit()
    logout_user()
    flash("You have successfully logged out.", "success")
    return redirect(url_for("auth.login"))

scoring_engine/web/views/flags.py
from flask import Blueprint, redirect, render_template, url_for
from flask_login import current_user, login_required

from scoring_engine.models.team import Team

mod = Blueprint("flags", __name__)


@mod.route("/flags")
@login_required
def home():
    if not (current_user.is_red_team or current_user.is_white_team):
        return redirect(url_for("auth.unauthorized"))

    return render_template("flags.html", teams=Team.get_all_blue_teams())

scoring_engine/web/views/injects.py
from datetime import datetime
from flask import Blueprint, render_template, url_for, redirect
from flask_login import login_required, current_user
from scoring_engine.models.inject import Inject, File
from scoring_engine.db import session


mod = Blueprint("injects", __name__)


@mod.route("/injects")
@login_required
def home():
    if not (current_user.is_blue_team or current_user.is_red_team):
        return redirect(url_for("auth.unauthorized"))
    return render_template(
        "injects.html"
    )


@mod.route("/inject/<inject_id>")
@login_required
def inject(inject_id):
    inject = session.query(Inject).get(inject_id)
    if (
        inject is None
        or not current_user.team == inject.team
        or datetime.utcnow() < inject.template.start_time
    ):
        return redirect(url_for("auth.unauthorized"))

    files = (
        session.query(File)
        .filter(File.inject_id == inject_id)
        .order_by(File.name)
        .all()
    )

    return render_template(
        "inject.html",
        inject=inject,
        files=files,
    )

scoring_engine/web/views/notifications.py
from flask import Blueprint, render_template

from scoring_engine.db import session
from scoring_engine.models.notifications import Notification

mod = Blueprint("notifications", __name__)


@mod.route("/notifications")
@mod.route("/notifications/unread")
def unread():
    # notification_count = session.query(Notification).filter(current_user).all()
    return render_template("notifications.html", notification_count=1)


@mod.route("/notifications/read")
def read():
    return render_template("notifications.html", notification_count=1)

scoring_engine/web/views/overview.py
from flask import Blueprint, render_template

from scoring_engine.models.team import Team

mod = Blueprint("overview", __name__)


@mod.route("/overview")
def home():
    return render_template("overview.html", teams=Team.get_all_blue_teams())

scoring_engine/web/views/profile.py
from flask import Blueprint, render_template
from flask_login import login_required

mod = Blueprint('profile', __name__)


@mod.route('/profile')
@login_required
def home():
    return render_template('profile.html')

scoring_engine/web/views/scoreboard.py
from flask import Blueprint, render_template

mod = Blueprint('scoreboard', __name__)


@mod.route('/scoreboard')
def home():
    return render_template('scoreboard.html')

scoring_engine/web/views/services.py
from flask import Blueprint, render_template, url_for, redirect
from flask_login import login_required, current_user
from scoring_engine.models.service import Service
from scoring_engine.models.setting import Setting
from scoring_engine.db import session


mod = Blueprint('services', __name__)


@mod.route('/services')
@login_required
def home():
    if not current_user.is_blue_team:
        return redirect(url_for('auth.unauthorized'))
    return render_template('services.html')


@mod.route('/service/<id>')
@login_required
def service(id):
    service = session.query(Service).get(id)
    if service is None or not current_user.team == service.team:
        return redirect(url_for('auth.unauthorized'))
    modify_hostname_setting = Setting.get_setting('blue_team_update_hostname').value
    modify_port_setting = Setting.get_setting('blue_team_update_port').value
    modify_account_usernames_setting = Setting.get_setting('blue_team_update_account_usernames').value
    modify_account_passwords_setting = Setting.get_setting('blue_team_update_account_passwords').value

    return render_template(
        'service.html',
        id=id,
        service=service,
        modify_hostname_setting=modify_hostname_setting,
        modify_port_setting=modify_port_setting,
        modify_account_passwords_setting=modify_account_passwords_setting,
        modify_account_usernames_setting=modify_account_usernames_setting
    )

scoring_engine/web/views/stats.py
from flask import Blueprint, jsonify, redirect, render_template, url_for
from flask_login import current_user, login_required
from sqlalchemy import desc
from sqlalchemy.sql import func

from scoring_engine.cache import cache
from scoring_engine.config import config
from scoring_engine.models.check import Check
from scoring_engine.models.round import Round
from scoring_engine.models.team import Team
from scoring_engine.db import session

import pytz

mod = Blueprint("stats", __name__)


@mod.route("/stats")
@login_required
def home():
    if not (current_user.is_blue_team or current_user.is_white_team):
        return redirect(url_for("auth.unauthorized"))

    return render_template("stats.html")

scoring_engine/web/views/welcome.py
from flask import Blueprint, render_template

from scoring_engine.models.setting import Setting

mod = Blueprint('welcome', __name__)


@mod.route('/')
@mod.route("/index")
def home():
    welcome_content = Setting.get_setting('welcome_page_content').value
    return render_template('welcome.html', welcome_content=welcome_content)

scoring_engine/web/templates/about.html
{% extends 'base.html' %}
{% block title %}About{% endblock %}

{% block head %}
    {{ super() }}
{% endblock %}

{% block content %}
<div class="container md-page" style="padding-bottom: 0px;">
  <div class="row">
  {{about_content|safe}}
  </div>
  <br>
  <div class="col-sm-8 col-sm-offset-2 text-center" >
    <ul class="list-inline center-block">
      <li><h5><a href="https://scoringengine.readthedocs.io/en/latest/installation.html">Setup your own!</a></h5></li>
      <li><h5>Version: {{version}}</h5></li>
      <li><h5><a href="https://github.com/scoringengine/scoringengine/issues/new">File a bug</a></h5></li>
    </ul>
  </div>
</div>
{% endblock %}

scoring_engine/web/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% block head %}
  <title>Scoring Engine - {% block title %}{% endblock %}</title>
  <script src="{{ url_for('static', filename='vendor/js/jquery.min.js') }}"></script>
  <script src="{{ url_for('static', filename='vendor/js/bootstrap.min.js') }}"></script>
  {% endblock %}
  <link href="{{ url_for('static', filename='vendor/css/bootstrap.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='vendor/css/bootstrap-glyphicons.css') }}" rel="stylesheet">
  <link rel="shortcut icon" href="{{ url_for('static', filename='images/favicon.ico') }}">
  <link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet">
</head>
{% if 'unauthorized' in request.path %}

<body style="background-color: red">
  {% else %}

  <body style="background-color: #f9f9f9;">
    {% endif %}
    <script>
      $(document).ready(function () {
        $("#alert-info").fadeTo(2000, 500).slideUp(500, function () {
          $("#alert-info").slideUp(500);
        });
      });
    </script>

    {% for category, message in get_flashed_messages(with_categories=true) %}
    <div class="alert alert-{{category}} alert-dismissable alert-fixed" id="alert-info" role="alert"
      style="margin-bottom: 0px">
      <button type="button" class="close" data-dismiss="alert">x</button>
      <strong>{{ message }}</strong>
    </div>
    {% endfor %}

    {% if "admin" in request.path %}
    <nav class="navbar navbar-collapse navbar-inverse" style="border-radius: 0 !important">
    <!-- <nav class="collapse navbar-collapse navbar-inverse" style="border-radius: 0 !important">-->
    {% else %}
    <nav class="navbar navbar-collapse navbar-inverse" style="border-radius: 0 !important">
    {% endif %}
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Scoring Engine</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse" aria-expanded="false" style="">
          <ul class="nav navbar-nav">
            <li class="navbar-item {% if request.path == '/scoreboard' %}active{% endif %}"><a class="nav-link" href="{{ url_for('scoreboard.home') }}">Scoreboard</a></li>
            <li class="navbar-item {% if request.path == '/overview' %}active{% endif %}"><a class="nav-link"  href="{{ url_for('overview.home') }}">Overview</a></li>
            {% if current_user.is_authenticated %}
              {% if current_user.is_blue_team %}
              <li class="navbar-item {% if request.path == '/services' %}active{% endif %}"><a class="nav-link"
                  href="{{ url_for('services.home') }}">Services</a></li>
              {% endif %}
              {% if current_user.is_blue_team or current_user.is_red_team %}
              <li class="navbar-item {% if request.path == '/injects' %}active{% endif %}"><a class="nav-link"
                  href="{{ url_for('injects.home') }}">Injects</a></li>
              {% endif %}
              {% if current_user.is_blue_team or current_user.is_white_team %}
              <li class="navbar-item {% if request.path == '/stats' %}active{% endif %}"><a class="nav-link"
                  href="{{ url_for('stats.home') }}">Stats</a></li>
              {% endif %}
              {% if current_user.is_red_team or current_user.is_white_team %}
              <li class="navbar-item {% if request.path == '/flags' %}active{% endif %}"><a class="nav-link"
                  href="{{ url_for('flags.home') }}">Flags</a></li>
              {% endif %}
              {% if current_user.is_white_team %}
              <li class="navbar-item {% if 'admin' in request.path %}active{% endif %}"><a class="nav-link"
                  href="{{ url_for('admin.status') }}">Admin</a></li>
              {% endif %}
              {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
              {% if not current_user.is_authenticated %}
              <li class="navbar-item"><a href="{{ url_for('auth.login') }}">Login</a></li>
              {% else %}
              <!-- <li class="navbar-item">
                <a href="{{ url_for('notifications.unread') }}">Notifications {% if notification_count %}<span
                    class="badge">{{ notification_count}}</span>{% endif %}</a>
              </li> -->
              <li class="dropdown">
                <a href="#" data-toggle="dropdown" class="dropdown-toggle navbar-item" style="margin-right: 20px;">{{
                  current_user.get_username }} <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="{{ url_for('profile.home') }}">Profile</a></li>
                  <li class="divider"></li>
                  <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
                </ul>
              </li>
              {% endif %}
              <li class="navbar-item"><a href="{{ url_for('about.about') }}">About</a></li>
            </ul>
          </div>
          <!--/.nav-collapse -->
        </div>
        <!--/.container-fluid -->
      </nav>
      {% block content %}
      {% endblock %}
  </body>

</html>

scoring_engine/web/templates/flags.html
{% extends 'base.html' %}
{% block title %}Stats{% endblock %}
{% block head %}
{{ super() }}
<script src="{{ url_for('static', filename='vendor/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendor/js/dataTables.bootstrap.min.js') }}"></script>
<link rel="stylesheet" href="{{ url_for('static', filename='vendor/css/dataTables.bootstrap.min.css') }}" />
{% endblock %}
{% block content %}
<div class="container-fluid md-page">
    <div class="row">
        <h2 class="text-center">Flags</h2>
    </div>
    <div class="row">
        <table id="flags" class="table table-striped table-bordered table-compact" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Start Time</th>
                    <th>End Time</th>
                    <th>Type</th>
                    <th>Platform</th>
                    <th>Permission</th>
                    <th>Path</th>
                    <th>Content</th>
                </tr>
            </thead>
        </table>
    </div>
    <div class="row">
        <table id="solves" class="table table-striped table-bordered table-compact" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th>ID</th>
                    {% for team in teams %}
                    <th>{{ team.name }}</th>
                    {% endfor %}
                </tr>
            </thead>
        </table>
    </div>
</div>
<script>
  $('#flags').DataTable( {
      ajax: '/api/flags',
      order: [[1, 'asc']],
      columns: [
        { data: 'id' },
        { data: 'start_time' },
        { data: 'end_time' },
        { data: 'type' },
        { data: 'platform' },
        { data: 'perm' },
        { data: 'path' },
        { data: 'content' }
      ],
  } );
</script>
<script>
    $("#solves").DataTable({
        ajax: "/api/flags/solves", // API endpoint to fetch data
        ordering: false,  // Disable ordering on all columns
        columns: [
            { data: 0, title: "ID" }, // First column for flag_id
            {% for team in teams %}
            { 
                data: "{{ loop.index0 }}", // Accessing the index for each team column
                title: "{{ team.name }}", 
                render: function (data, type, row) {
                    // Render checkmark for true, X for false
                    return data 
                        ? "<span class='glyphicon glyphicon-ok' style='color: green'></span>" 
                        : "<span class='glyphicon glyphicon-remove' style='color: red'></span>";
                }
            },
            {% endfor %}
        ]
    });
</script>
{% endblock %}

scoring_engine/web/templates/inject.html
{% extends 'base.html' %}
{% block title %}Inject{% endblock %}
{% block head %}
{{ super() }}
<script src="{{ url_for('static', filename='vendor/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendor/js/dataTables.bootstrap.min.js') }}"></script>
<link rel="stylesheet" href="{{ url_for('static', filename='vendor/css/dataTables.bootstrap.min.css') }}" />
<link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet">

<script src="{{ url_for('static', filename='vendor/js/bootstrap-editable.min.js') }}"></script>
<link href="{{ url_for('static', filename='vendor/css/bootstrap-editable.css') }}" rel="stylesheet" />

<!-- Dropzone -->
<script src="{{ url_for('static', filename='vendor/js/dropzone.min.js') }}"></script>
<link href="{{ url_for('static', filename='vendor/css/dropzone.min.css') }}" rel="stylesheet" />

<!-- Moment -->
<script src="{{ url_for('static', filename='vendor/js/moment.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendor/js/moment-timezone.min.js') }}"></script>

{% endblock %}
{% block content %}
<div class="container md-page">
  <div class="row">
    <div class="col-sm-3 lefthand-nav" style="padding-top: 20px;">
      <div id="inject_navbar" class="list-group"></div>
    </div>
    <div class="col-sm-9">
      {% if inject.status == 'Submitted' %}
      <h3>{{ inject.template.title }} <span class="label label-success">{{ inject.status}}</span></h3>
      {% elif inject.status == 'Graded' %}
      <h3>{{ inject.template.title }} <span class="label label-info">{{ inject.status}}</span></h3>
      {% elif inject.template.expired %}
      <h3>{{ inject.template.title }} <span class="label label-danger">Expired</span></h3>
      {% elif inject.status == 'Draft' %}
      <button type="button" class="btn btn-primary pull-right" data-toggle="modal"
        data-target="#submitInjectConfirmation">Submit Inject</button>
      <h3>{{ inject.template.title }} <span class="label label-warning">{{ inject.status}}</span></h3>
      {% else %}
      <h3>{{ inject.template.title }}</h3>
      {% endif %}
      <!-- <h5>Status</h5> -->
      <h5>Points - {{ inject.score }}</h5>
      <h5>Start Time - <div id="startTime">{{ inject.template.start_time }}</div>
      </h5>
      <h5>End Time - <div id="endTime">{{ inject.template.end_time }}</div>
      </h5>
      <h4>Scenario</h4>
      <p>{{ inject.template.scenario }}</p>
      <h4>Deliverable</h4>
      <p>{{ inject.template.deliverable }}</p>
      {% if inject.template.rubric %}
      <h4>Rubric</h4>
      <table class="table table-bordered">
        <tr>
          <th>Deliverable</th>
          <th>Value</th>
        </tr>
        {% for rubric in inject.template.rubric %}
        <tr>
          <td>{{ rubric.deliverable }}</td>
          <td>{{ rubric.value }}</td>
        </tr>
        {% endfor %}
      </table>
      {% endif %}
      <!-- <h5>Submitted</h5>
      <h5>Submitted By</h5>
      <h5>Created</h5>
      <h5>Graded</h5> -->
      <div class="row">
        <div class="well">
          <form class="dropzone" id="file-upload"></form>
        </div>
      </div>
      <h4>Files</h4>
      <div id="files">
      </div>
      <h4>Comments</h4>
      <div id="comments">
      </div>
      <div class="panel panel-default">
        <div class="panel-body">
          <form>
            <div class="form-group">
              <textarea id="commentArea" class="form-control" rows="3"></textarea>
            </div>
            <div class="form-group">
              <button id="addCommentButton" type="button" class="btn btn-primary">Comment</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Submit Modal -->
<div class="modal fade" id="submitInjectConfirmation" tabindex="-1" role="dialog"
  aria-labelledby="submitInjectConfirmationLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
            aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Submit Inject</h4>
      </div>
      <div class="modal-body">
        <input type="hidden" name="injectId" id="injectId" value="{{ inject.id }}" />
        <p>Are you sure you want to submit this inject?</p>
        <p><b>You will not be able to edit this inject after submitting.</b></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <button type="button" id="injectSubmitConfirmButton" class="btn btn-primary">Submit</button>
      </div>
    </div>
  </div>
</div>
<script>
  $(document).ready(function () {
    // Update Timestamps
    var startTime = moment.utc($('#startTime').text()).tz(moment.tz.guess()).format('YYYY-MM-DD HH:mm:ss z');
    var endTime = moment.utc($('#endTime').text()).tz(moment.tz.guess()).format('YYYY-MM-DD HH:mm:ss z');
    var startTimeRelative = moment.utc($('#startTime').text()).tz(moment.tz.guess()).fromNow();
    var endTimeRelative = moment.utc($('#endTime').text()).tz(moment.tz.guess()).fromNow();
    $('#startTime').text(startTime + ' (' + startTimeRelative + ')');
    $('#endTime').text(endTime + ' (' + endTimeRelative + ')');
    // $('#endTime').text(' (' + moment($('#endTime').text()).fromNow() + ')');

    // Load navbar and update every 30 seconds
    updateInjects();
    setInterval(updateInjects, 30000);

    // Load comments and update every 30 seconds
    updateComments();
    setInterval(updateComments, 30000);

    // Load files and update every 30 seconds
    updateFiles();
    setInterval(updateFiles, 30000);
  });
</script>
<script>
  // Delete Template Confirmation
  $('#injectSubmitConfirmButton').unbind().click(function () {
    console.log('Inject Submitted');
    const injectId = $('#injectId').val();
    $.ajax({
      url: "/api/inject/" + injectId + "/submit",
      type: 'POST',
      success: function (result) {
        $('#submitInjectConfirmation').modal('hide');
        location.reload();  // Reload page
      },
      error: function (result) {
        console.error(result['responseJSON']['status']);
      }
    });
  });
</script>
<script>
  function updateInjects() {
    // Query API for files
    $.ajax({
      url: "/api/injects",
      success: function (result) {
        console.log($(location).attr("pathname"));

        var navbar = "";

        // Append navabar elements
        $.each(result.data, function (index, value) {
          navbar += '<a href="/inject/' + value.id + '" class="list-group-item';
          if ($(location).attr("pathname") == "/inject/" + value.id) {
            navbar += ' active';
          }
          navbar += '">' + value.title + '</a>';
        });

        // Update navbar
        $("#inject_navbar").html(navbar);
      },
      error: function (result) {
        console.error("An Error Occurred Querying For Files");
      }
    });
  };
</script>
<script>
  function updateFiles() {
    // Query API for files
    $.ajax({
      url: "/api/inject/{{ inject.id }}/files",
      success: function (result) {
        var files = '';

        // Append new files
        $.each(result.data, function (index, value) {
          files += "<p><a href='/api/inject/{{ inject.id }}/files/" + value.id + "/download'>" + value.name + "</a></p>";
        });

        // Update navbar
        $("#files").html(files);
      },
      error: function (result) {
        console.error("An Error Occurred Querying For Files");
      }
    });
  };
</script>
<script>
  Dropzone.options.fileUpload = {
    url: '/api/inject/{{ inject.id }}/upload',
    init: function () {
      this.on("success", file => {
        console.log("A file has been successfully uploaded");
        updateFiles();
      });
      this.on("error", file => {
        console.error("An error occurred while uploading a file");
      });
    }
  };
</script>
<script>
  function updateComments() {
    // Query API for files
    $.ajax({
      url: "/api/inject/{{ inject.id }}/comments",
      success: function (result) {
        var comments = ""

        // Append comment elements
        $.each(result.data, function (index, value) {
          if (value.team == "{{ current_user.team.name }}") {
            comments += '<div class="panel panel-primary">' +
              '<div class="panel-heading">' + value.user + ' (' + value.team + ') commented on ' + value.added + '</div>' +
              '<div class="panel-body">' + value.text + '</div></div>';
          } else {
            comments += '<div class="panel panel-default">' +
              '<div class="panel-heading">' + value.user + ' (' + value.team + ') commented on ' + value.added + '</div>' +
              '<div class="panel-body">' + value.text + '</div></div>';
          }
        });

        // Update comments
        $("#comments").html(comments);
      },
      error: function (result) {
        console.error("An Error Occurred Querying For Files");
      }
    });
  };
</script>
<script>
  $('#addCommentButton').unbind().click(function () {
    $.ajax({
      url: "/api/inject/{{ inject.id }}/comment",
      type: "POST",
      contentType: "application/json",
      data: JSON.stringify({
        comment: $('#commentArea').val()
      }),
      success: function (result) {
        console.log("Comment added");
        $('#commentArea').val('');
        updateComments();
      },
      error: function (result) {
        alert(result.responseJSON['status']);
        console.error("ERROR:", result.responseJSON['status']);
      }
    });
  });
</script>
{% endblock %}

scoring_engine/web/templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block head %}
    {{ super() }}
    <link href="{{ url_for('static', filename='css/signin.css') }}" rel="stylesheet">
{% endblock %}
{% block content %}
<div class="container md-page">
    <form method="POST" role="form" class="form-signin">
        {{ form.csrf_token }}
        <h2 class="form-signin-heading">Please sign in</h2>
        <label for="inputUsername" class="sr-only">Username</label>
        {{ form.username() }}
        <label for="inputPassword" class="sr-only">Password</label>
        {{ form.password() }}
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
    </form>
</div>
{% endblock %}

scoring_engine/web/templates/notifications.html
{% extends 'base.html' %}
{% block title %}About{% endblock %}

{% block head %}
{{ super() }}
{% endblock %}

{% block content %}
<div class="container md-page" style="padding-bottom: 0px;">
  <div class="page-header">
    <h3>Notifications</h3>
  </div>
  <div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-body">
      <ul class="nav nav-tabs">
        <li role="navigation" {% if request.path=='/notifications/unread' %}class="active" {% endif %}><a
            href="/notifications/unread">Unread{% if notification_count %} <span class="badge">{{ notification_count
              }}</span>{% endif %}</a></li>
        <li role="navigation" {% if request.path=='/notifications/read' %}class="active" {% endif %}><a
            href="/notifications/read">Read</a></li>
      </ul>
      <!-- Table -->
      <table class="table table-bordered">
        <tbody>
          <tr>
            <td>
              <a href="/admin/injects/1">An inject is ready to be graded</a>
            </td>
            <td>Team 1</td>
            <td>Journey to Mordor</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>
<script>
    // Query API for notifications
    $.ajax({
      url: "/api/notifications",
      success: function (result) {
        // Append new files
        $.each(result.data, function (index, value) {
          files += "<p><a href='/" + value.id + "/download'>" + value.name + "</a></p>";
        });

        // Update navbar
        $("#files").html(files);
        console.log(files);
      },
      error: function (result) {
        console.error("An Error Occurred Querying For Files");
      }
    });
</script>
{% endblock %}

scoring_engine/web/templates/unauthorized.html
{% extends 'base.html' %}
{% block title %}Unauthorized{% endblock %}
{% block content %}
<div class="container">
  <div class="row">
      <img class="center-block" style="border-style: solid; border-width: 5px;" src="{{ url_for('static', filename='images/unauthorized.gif') }}">
  </div>
</div>
{% endblock %}

scoring_engine/web/templates/welcome.html
{% extends 'base.html' %}
{% block title %}Welcome{% endblock %}
{% block head %}
    {{ super() }}
    <link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet">
{% endblock %}
{% block content %}
<div class="container md-page">
  {{welcome_content|safe}}
</div>
{% endblock %}